### PR TITLE
change inputmask to ios

### PR DESCRIPTION
**Pull request by Eaffy**
# Summary

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by RageOfJustice** [comment]
Hi! tried your PR.
image

**Comment by acollazomayer** [comment]
Is this podspec working?

**Comment by Eaffy** [comment]
> Is this podspec working?

I found a new way to install react-native-text-inout-mask via cocoapods.

**Comment by Eaffy** [comment]
As I has commented, I installed react-native-text-inout-mask by Private Pods. It work well for me, so I close this pull request

**Pull request closed without merging**
