### PR TITLE
Changes to work with pods integration.

### PR DESCRIPTION
**Pull request by waqas19921**
# Summary

* What is the feature?
Added functionality for pods integration.

* What areas of the library does it impact?
It will impact the imports for older version of react native.

### What's required for testing (prerequisites)?
Create new project using react native version `0.60.5`
Link the library manually and it will work.

### What are the steps to reproduce (after prerequisites)?
Create new project using react native version `0.60.5`.
Currently it will not work even after manual linking.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [X] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by betoharres** [comment]
Hi @waqas19921 Thanks a lot for helping the library! It will help me a lot! =] I'll try your modifications right now :) Thanks again :heart:

**Comment by waqas19921** [comment]
@cesargdm Please suggest any changes. There is no template for `changelog` file. I have added some basic changes in `CHANGELOG.md`.

**Comment by cesargdm** [comment]
> @cesargdm Please suggest any changes. There is no template for `changelog` file. I have added some basic changes in `CHANGELOG.md`.

```
## Changelog

### Version 2.0.0

* Updated the headers in `RNTextInputMask.m` file to work with pods integration
```

Should be enough, as 2.0.0 is a breaking change

**Comment by waqas19921** [comment]
@cesargdm done. Thanks for the suggestion.

**Comment by browniefed** [comment]
Any chance to get this merged? Would be great to have a version working w/ v.60+

**Comment by vshab** [comment]
Maybe release a new version?

**Comment by cesargdm** [comment]
Waiting to add the PodFile

**Comment by yuriedmundo** [comment]
When new release?

**Comment by waqas19921** [comment]
@cesargdm It will work with `RN 0.60.5` with manual integration.
Usage with pods through auto linking will not work as currently the swift code or usage of frameworks is not supported  in `RN 0.60.5`. Need to wait for following pull request to be released.
https://github.com/facebook/react-native/pull/25619

**Comment by waqas19921** [comment]
Pods integrations with use of swift code or libs will be supported in `RN 0.61`

**Comment by acollazomayer** [comment]
@waqas19921 Any news on the podspec?

**Comment by acollazomayer** [comment]
@waqas19921 Any news on the podspec

**Comment by waqas19921** [comment]
> Waiting to add the PodFile

@cesargdm Have a look on this pull request https://github.com/react-native-community/react-native-text-input-mask/pull/140

**Comment by waqas19921** [comment]
> Waiting to add the PodFile

@cesargdm Have a look on this pull request https://github.com/react-native-community/react-native-text-input-mask/pull/140

**Pull request merged**
