### PR TITLE
Fix for react native warning on componentWillReceiveProps

### PR DESCRIPTION
**Pull request by alexnaiman**
# Summary
Fixed componentWillReceiveProps warning

* What issues does the pull request solve? 
	#133 
* How did you implement the solution?
	I changed the lifecycle method from `componentWillReceiveProps` to `componentDidUpdate`
* What areas of the library does it impact?
	The JS part of the library
### What's required for testing (prerequisites)?
	Empty project with the library installed

### What are the steps to reproduce (after prerequisites)?
	Run the app and check if the masking it is still working

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅	   |
| Android |    ✅   	  |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by iagorm** [comment]
can someone review this PR?

**Comment by jonassvalin** [comment]
Anyone? This is important to fix as componentWillReceiveProps will be removed in RN 0.17

**Comment by lundn** [comment]
Can this be merged?

**Comment by walterholohan** [comment]
Are their any maintainers left on this repo?

**Comment by eltoncostadev** [comment]
Hey, shall we merge the pull request????

**Comment by warrenalphonso** [comment]
Merge this!!! Is there someone we can contact who has write access?

**Comment by SrBrahma** [comment]
This is merged but not implemented in the actual NPM package. Please, someone deploy this new version.

**Comment by seriousStar** [comment]
Please merge this. or there is no one to do it? it seems RN team doesn't work.

**Comment by SrBrahma** [comment]
Was using the

> @ivanzotov This is merged but not implemented in the current NPM package (2.0.0). Please, someone deploy this new version.
> 
> Edit: I am using this PR with
> `npm i react-native-community/react-native-text-input-mask#pull/141/head`

I was using this solution, but this PR doesn't include the podspec for iOS, that was implemented in the package after this PR. Can someone save me?

**Comment by johnny-vikrant** [comment]
@ivanzotov Please release a new version with this PR. Thanks.

**Comment by diegormb06** [comment]
@ivanzotov Please release a new version with this fixes

**Comment by vikrantnegi** [comment]
@kelset Need help. The maintainer seems to be too busy. Thanks.

**Comment by jotahws** [comment]
Any updates on this?

**Comment by kelset** [comment]
No updates on my side, I was not able to get in contact with the mantainer.

Maybe @brentvatne had any luck? Since I noticed the repo has been moved to its own org, I guess it means someone has write level admins over it.

**Comment by jhonattansolartearanda** [comment]
Any updates on this?

**Comment by acollazomayer** [comment]
Any updates?

**Comment by kelset** [comment]
I've asked again in the RN core discord, and Brent said that basically @ivanzotov is the sole owner of this so I've tried asking directly [to him on twitter](https://twitter.com/Kelset/status/1354375523393265666) 🤷‍♂️

**Comment by ivanzotov** [comment]
I've release 2.0.1 that includes this PR. It's probably the last release from my side, because I don't have time to maintain this project anymore. If anyone would like to maintain this please let me know. Thanks!

**Pull request merged**
