### PR TITLE
Upgrading to Swift 4.2 for Xcode 10.2

### PR DESCRIPTION
**Pull request by gdhillon-pbl**
Upgrading to Swift 4.2 for Xcode 10.2

### CODE REVIEW

**Comment by gdhillon-pbl** [comment]
Fixes https://github.com/react-native-community/react-native-text-input-mask/issues/107

**Comment by amitassaraf** [comment]
@skb1129 Can you merge & release?

**Comment by skb1129** [comment]
I don't have access.
@ivanzotov, can you help?

**Comment by antonsivogrivov** [comment]
Any updates?

**Comment by jin-quicksafety** [comment]
Anything??

**Pull request merged**
