### PR TITLE
fix mask/text update on rn v0.56

### PR DESCRIPTION
**Pull request by artyorsh**
**Problem:**
Running RN 0.56.0 TextInputMask for any reason won't dynamically update mask/text (iOS).
**Steps to reproduce:**
On RN 0.56.0
1. Input some text
2. Create some event (like button press) which should change component state (value/mask)
3. TextInputMask is not updated.

See [example branch](https://github.com/artyorsh/react-native-text-input-mask/tree/example) containing preview app with fix.

### CODE REVIEW

**Comment by oblador** [comment]
@artyorsh This PR is changing code formatting from without semi colons to with. Think it's good practice to respect the existing formatting so it's easier for the author to review your changes. Would you mind reverting the new formatting?

**Comment by artyorsh** [comment]
@oblador 
Thanks for notice.
Done

**Comment by dharamEnest** [comment]
@artyorsh bro issue is still there  [https://ibb.co/n796Fz](url) please check this on clear component state the ( display there i need to clear this then the state is clear.

**Comment by derenebdon** [comment]
When I tried to use this PR to fix an iOS issue where a custom clear button wasn't working, I ended up getting an endless loop when multiple keys were pressed at the same time.  I ended up only taking a portion of this PR due to that reason.  Also a change to the import style in the iOS native module caused a build failure for me in release mode.

**Comment by lfkwtz** [comment]
as @derenebdon mentioned - this seems to have introduced a bug where the input will be stuck in an event loop if you enter text rapidly

**Pull request closed without merging**
