### PR TITLE
Sets always embed swift libraries to NO

### PR DESCRIPTION
**Pull request by cassianomon**
Fix https://github.com/react-native-community/react-native-text-input-mask/issues/22

### CODE REVIEW

**Comment by cassianomon** [comment]
@ivanzotov You can merge this?

**Comment by kvandake** [comment]
Any progress?

**Comment by cassianomon** [comment]
Changed to this library: https://github.com/benhurott/react-native-masked-text

**Comment by kvandake** [comment]
I switched to this library too ;)

**Comment by ivanzotov** [comment]
Thank you for the PR, I recreated the library in v1.0.0, so it is now disabled by default

**Pull request closed without merging**
